### ISSUE TITLE
Dock

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_kv_dlg#10]
Как встроить длг через Dlg_dock, где его хендл? И для sidebar plugin нужен хендл

**Comment by kvichans** [comment]
Не понял вопрос. Аг лишь посредник. Если можно получить такой хендл через штатное АПИ, то добавлю метод-опрос.

**Comment by Alexey-T** [comment]
Нужен метод чтоб получить хендл диалога

**Comment by kvichans** [comment]
ToDo

**Comment by Alexey-T** [comment]
?

**Comment by kvichans** [comment]
ag.fhandle()

**Comment by Alexey-T** [comment]
некрасивые имена. Лучше f_handle c_handle

**Comment by kvichans** [comment]
это (частично) принятая стилистика - не делить на слова, а сливать - например, str.startswith
