### ISSUE TITLE
Translate problems

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_kv_dlg#12]
@medvosa Я обновил исходник и первую версию перевода страниц [Обзор](https://github.com/kvichans/cuda_kv_dlg/wiki/Review-(ru))/[Review](https://github.com/kvichans/cuda_kv_dlg/wiki/Review).

1. Подозреваю ошибку перевода
`указывающий на имя контрола, по которому будет равнение`
`indicating the name of the control, which will be aligned`
Я обратно перевожу так: 
*указывающий на имя контрола, который будет выравнен*
@Alexey-T Так нормально:
`У контрола, который требует выравнивания, нужно задать tid, указывающий на имя контрола, по которому будет равнение` 
`If control needs alignment tid must be referensing control's name by which the alignment is done`

**Comment by Alexey-T** [comment]
это я решу.

**Comment by Alexey-T** [comment]
Так нормально

**Comment by Alexey-T** [comment]
поправил review немного. ок?
