### ISSUE TITLE
Inf

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_kv_dlg#13]
Utilities create and support dialog

— Helper library to work with CudaText plugin dialogs

caption=Tuning vertical alignment for text into control pairs

— Adjust vertical alignment of controls pairs

**Comment by kvichans** [comment]
Спасибо

**Comment by kvichans** [comment]
> Adjust vertical alignment of controls pairs

Нет. Нужно явно упомянуть, что выравнивание будет по текстам

**Comment by Alexey-T** [comment]
Adjust vertical alignment of controls by text

**Comment by kvichans** [comment]
Adjust vertical alignment of control pairs by text
Лучше так?

**Comment by Alexey-T** [comment]
да

**Comment by Alexey-T** [comment]
fixed?
