### ISSUE TITLE
why not bool (list) here

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_kv_dlg#16]
`val` for `clbx` /`checklistbox` and `clvw` / `checklistview` can be specified as `(7,['0','1',...])`:

**Comment by kvichans** [comment]
ToDo: добавить тест, что оба варианта подходят

**Comment by Alexey-T** [comment]
?

**Comment by kvichans** [comment]
Была недоделка - поправил
Теперь можно список из False/True подавать
