### ISSUE TITLE
Return vals 

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_kv_dlg#3]
После этого можно закрыть диалог (вернуть None), ничего не менять (вернуть []) 

Наверно лучше не none / [], а false/none

**Comment by kvichans** [comment]
Тут логика построена на предположении, что обработчик будет набирать в список/словарь то, что хочет изменить. Значит пустой список/словарь может сложиться из-за логики внутри обработчика.
А вот приравнять реакции Аг на возврат False и None - это мне нравится.

**Comment by kvichans** [comment]
Оказалось, что на возвращаемое из перехвата значение нагружено еще больше (увы):
1. Если None, то закрыть диалог
2. Если False, то (может быть) прервать цепочку перехватов
3. Если коллекция, то внести изменения в форму

Пока оставлю как было - буду наблюдать и думать

**Comment by kvichans** [comment]
Тесты и применения (в cuda_ext) показали, что нужно оставить как есть
