### ISSUE TITLE
DlgMenu

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_kv_dlg#4]
Вместо них в плагине предлагается использовать метод объекта DlgAg

Может стоит сделать объект для меню, а не делать процедурную обертку?

**Comment by kvichans** [comment]
Есть над чем тут подумать...

**Comment by kvichans** [comment]
Выделил основную часть в отдельную функцию модуля (на класс там не набралось функциональности):
```python
def show_menu(mn_content, x, y, ag=None, repro_to_file=None)
```
Описал ее в вики

В методе
```python
def show_menu(self, mn_content, name, where='+h', dx=0, dy=0, repro_to_file=None):
```
остались действия по привязке меню к контролу `name`

Теперь можно вызывать или от `DlgAg()` или вообще не создавая `DlgAg`.
