### ISSUE TITLE
Dirty name

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_kv_dlg#5]
'negative_xy_as_reflex
Лучше negative_coords

**Comment by Alexey-T** [comment]
Лучше так - neg_reflect

**Comment by kvichans** [comment]
negative_coords_as_reflex ?

**Comment by Alexey-T** [comment]
Negative_coords_reflect

**Comment by kvichans** [comment]
ОК

**Comment by kvichans** [comment]
Заменил на `negative_coords_reflect`
