### ISSUE TITLE
Delete/add controls

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_kv_dlg#6]
Как добавлять контролы и удалять? Только прятать можно? Прятать а не удалять- ок. Добавлять нужно например по клику кнопки

**Comment by Alexey-T** [comment]
При добавлении нужно ещё менять табордерс

**Comment by kvichans** [comment]
Аг не дает способа добавлять/удалять.
Мой опыт подсказывает, что показывать/прятать - практичнее.

`tab_order` - обычный атрибут. Можно задавать его в описании при перехватах, когда отображаются/скрываются контролы.

**Comment by Alexey-T** [comment]
А как палитра покажет к вариантов палитры?

**Comment by kvichans** [comment]
Каждый вариант палитры - отдельная форма

**Comment by kvichans** [comment]
Ой, чушь сказал.
Про палитру - пока не знаю

**Comment by kvichans** [comment]
Может и не чушь :)
Ничего не мешает, при выборе типа (из комбо) действительно запускать другой диалог.

**Comment by kvichans** [comment]
Будет метод `reset` с такими же параметрами как у конструктора. От предыдущего диалога сохранится только IDD.

**Comment by Alexey-T** [comment]
Ок

**Comment by kvichans** [comment]
Добавил `reset`
