### ISSUE TITLE
Child forms

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_kv_dlg#7]
Как делать одну форму дочкой второй и менять ее client coord и anchors?

**Comment by Alexey-T** [comment]
Для форм кажись нельзя. А как делать одну panel дочкой второй panel? И потом на неё класть кнопки?

**Comment by kvichans** [comment]
Для вложенных панелей действует атрибут `p` (parent)? Это нужно тестировать? Я действительно еще ни разу не делал из панелей матрешку.

**Comment by Alexey-T** [comment]
Хотя бы один тест

**Comment by kvichans** [comment]
ToDo

**Comment by Alexey-T** [comment]
?

**Comment by kvichans** [comment]
Работает
![изображение](https://user-images.githubusercontent.com/7419630/55620072-ad943300-57a2-11e9-9180-f25d81802492.png)
Объявления контролов
```python
    ,('bt1',dict(tp='bttn',cap='out button'             ,x= 0   ,au=True,y=  0              ))
    ,('pn1',dict(tp='panl'                              ,x=10   ,w=180  ,y= 30  ,h=100  ,border=True))
    ,('bp1',dict(tp='bttn',cap='button in p1'   ,p='pn1',x=30   ,au=True,y=  0              ))
    ,('pn2',dict(tp='panl'                      ,p='pn1',x=10   ,w=160  ,y= 30  ,h= 50  ,border=True))
    ,('bp2',dict(tp='bttn',cap='button in p2'   ,p='pn2',x=60   ,au=True,y=  0              ))
```

**Comment by Alexey-T** [comment]
спасибо.
